<?php $catalogLink = '- <a href="http://www.forum-russian.ru" title="Каталог форумов России" target="_blank">Каталог российский форум - региональные форумы России</a> 
- <a href="http://www.morshansk.su" title="Работа в Моршанске" target="_blank">Объявления о <b>работе в Моршанске</b> вакансии, моршанский форум</a> 
- <a href="http://www.myug.ru" title="Форум ЮГа России - отдых на Кубани" target="_blank"><b>Отдых на курортах Кубани</b> в 2010 году - лечение в горячем ключе заказать путёвку</a> 
- <a href="http://www.job-in-sochi.ru" title="Вакансии в Сочи - работа в Красной Поляне" target="_blank">Поиск <b>работы в Сочи</b> на форуме. Олимпийские стройки в Сочи</a> 
- <a href="http://forum-abkhazia.ru/forumdisplay-f_15.html" title="найти работу в Абхазии" target="_blank">Объявления о работа в Абхазии - вакансии в Абхазии</a>
- <a href="http://buysochi.ru" title="где найти работу в Сочи" target="_blank"><b>работа в Адлере</b> поиск вакансий в Сочи</a> 
- <a href="http://buysochi.ru/viewtopic.php?id=475" title="пепел от сигарет">Покупаем дорого <b>пепел от сигарет</b> - продажа пепла сигарет</a> 
- <a href="http://WebKuban.com" title="Сайты Краснодарского Края" target="_blank">Сайты Краснодарского края - <b>Каталог сайтов Кубани</b></a> 
- <a href="http://forum-abkhazia.ru" title="абхазский форум - отдых в Абхазии форум отзывов" target="_blank"><b>отзыв про Абхазию</b> - снять дом в Абхазии летом - форум Страны Души</a> 
- <a href="http://forum.allsochi.info/forumdisplay.php?f=85" title="отзвы абхазия - про отдых в Абхазии">Абахзия отзывы о том как я провёл лето в Абхазии</a>
- <a href="http://forum-abkhazia.ru/forumdisplay-f_14.html" title="купить квартиру в Абхазии" target="_blank"><b>купить дом в Абхазии</b> недвижимость в Абхазии может купить</a> 
- <a href="http://www.forum-crimea.ru">открылся новый <strong>форум Крыма</strong> об отдыхе на крымском полуострове в Ялте</a> 
- <a href="http://forum.allsochi.info/forumdisplay.php?f=3" title="информация о погоде в Сочи" target'; include '../view.php';