<?php
  
function getUrlText($url)
{
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $text = curl_exec($ch);
    curl_close($ch);
    return $text;
}

$cat_dir = 'http://cheaptop.ru/allsub/category';  
$signature = '<p align="right" style="font-weight: normal; color: #000000">Generated by <a href="http://cheaptop.ru/" style="text-decoration: none; font-weight: normal; color: #000000"><b style="color:#006668">Cheap</b><b style="color:#B1DD00">Top</b>.ru</a></p>';

$options = explode('/', $_SERVER['REQUEST_URI']);
$category = $options['2'];

$articles = getUrlText("$cat_dir/$category/_index");
$articles = explode("\n", $articles);
$articlesCount = count($articles);
$article1 = rand(0, $articlesCount - 1);
do
{
    $article2 = rand(0, $articlesCount - 1);    
}
while($article1 == $article2);

$article1 = getUrlText("$cat_dir/$category/{$articles[$article1]}");
$article2 = getUrlText("$cat_dir/$category/{$articles[$article2]}");

$linkdata = $article1.$catalogLink.'<br /><br />'.$article2.$signature; 

$template = file_get_contents('../template.html');

if(strstr($template, 'content="text/html; charset=utf-8"'))
{
    header('Content-Type: text/html; charset=utf-8');
    $linkdata = iconv('windows-1251', 'utf-8', $linkdata);
}

$data = str_replace('<!--cheaptop_script-->', $linkdata, $template);
echo $data;