<?php $catalogLink = '<a href="http://www.sdki.ru"  target="_blank" title="доски объявлений"><b>доски объявлений</b></a> по различным областям деятельности: <a href="http://www.sdki.ru/board/raz_auto.html" target=_blank>Автомобили</a>,
<a href="http://www.sdki.ru/board/raz_business.html" target=_blank>Бизнес</a>,
<a href="http://www.sdki.ru/board/raz_ofis.html" target=_blank>Для офиса</a>,
<a href="http://www.sdki.ru/board/raz_internet.html" target=_blank>Интернет, сайты</a>,
<a href="http://www.sdki.ru/board/raz_neft_gaz.html" target=_blank>Нефть, газ, уголь </a>,
<a href="http://www.sdki.ru/board/raz_les.html" target=_blank>Лесная промышленность</a>,
<a href="http://www.sdki.ru/board/raz_uslugi.html" target=_blank>Услуги</a>,
<a href="http://www.sdki.ru/board/raz_st.html" target=_blank>Стройматериалы</a>,
<a href="http://www.sdki.ru/board/raz_stroiprom.html" target=_blank>Бытовые товары</a>,
<a href="http://www.sdki.ru/board/raz_oborudovan.html" target=_blank>Оборудование</a>,
<a href="http://www.sdki.ru/board/raz_nedvizhimo.html" target=_blank>Недвижимость</a>,
<a href="http://www.sdki.ru/board/raz_produkt.html" target=_blank>Продукты, пищевая промышленность</a>,
<a href="http://www.sdki.ru/board/raz_job.html" target=_blank>Работа</a>,
<a href="http://www.sdki.ru/board/raz_metall.html" target=_blank>Металлы</a>,
<a href="http://www.sdki.ru/board/raz_him.html" target=_blank>Химия</a>,
<a href="http://www.sdki.ru/board/raz_stroy.html" target=_blank>Строительные</a>,
<a href="http://www.sdki.ru/board/raz_otdix.html" target=_blank>Отдых</a>,
<a href="http://www.sdki.ru/board/raz_tara.html" target=_blank>Тара, упаковка</a>,
<a href="http://www.sdki.ru/board/raz_collecting.html" target=_blank>Коллекционирование</a>,
<a href="http://www.sdki.ru/board/raz_beauty_health.html" target=_blank>Красота и здоровье</a>.'; include '../view.php';